function stringsToObject (actions) {
  return actions
    .trim()
    .split(/\s+/)
    .reduce((obj, action) => {
      obj[action] = action
      return obj
    }, {})
}

export default {
  // API_URL: 'http://localhost:7025/',
  // API_URL: 'http://10.132.50.70:8080/tax/api/',
  API_URL: 'http://dev.jamax.ba/taxapi/',
  // API_URL: 'http://10.132.50.30/taxapi/',
  // API_URL: 'http://localhost:7025/',
  // API_URL: 'http://10.132.50.30/taxapi/',

  ACTIONS: stringsToObject(`
    REQUEST_PROPERTY_FILTERS
    RECEIVE_PROPERTY_FILTERS
    ADD_PROPERTY_PETITIONER
    CREATE_CASE
    RECEIVE_CASE
    REQUEST_CASE
    UPDATE_AGE_RANGE
    UPDATE_SF_RANGE
    REQUEST_SINGLE_PROPERTY
    RECEIVE_SINGLE_PROPERTY
    REQUEST_SEARCH_PROPERTY
    RECEIVE_SEARCH_PROPERTY
    REQUEST_PROPERTY_DATA
    RECEIVE_PROPERTY_DATA
    UPDATE_PROPERTIES_BY_AGE_RANGES
    UPDATE_PROPERTIES_BY_SF_RANGES
    RESET_PIN_STATE
    UPDATE_PROPERTY_PETITIONER
    FILTER_PROPERTY_DATA
    SORT_PROPERTY_DATA
    RECEIVE_SELECTED_PROPERTIES
    ADD_SELECTED_PROPERTY
    UPDATE_CLASS_CODE
    UPDATE_TOWNSHIP
    CALCULATE_ASSESTMENT
    REQUEST_DOCUMENT_GENERATE
    REQUEST_RESAPPEAL_DOCUMENT_GENERATE
    REQUEST_COMPLAINT_DOCUMENT_GENERATE
    REQUEST_CALCULATION_EXCEL_DOCUMENT
    RECEIVE_CALCULATION_EXCEL_DOCUMENT
    RECEIVE_DOCUMENT_GENERATE
    RECEIVE_COMPLAINT_DOCUMENT_GENERATE
    RECEIVE_REREVIEW_DOCUMENT_GENERATE
    RECEIVE_RESAPPEAL_DOCUMENT_GENERATE
    RECEIVE_OWNERLESSEVERF_DOCUMENT_GENERATE
    LOG_USER_IN
    LOG_USER_OUT
    USER_LOGGED_IN
    USER_LOGGED_OUT
    USER_LOGIN_FAILED
    GET_USER_AUTH
    REGISTER_NEW_USER
    REGISTER_NEW_USER_SUCCESS
    REQUEST_ALL_CASES
    RECEIVE_ALL_CASES
    SET_ERROR_MESSAGE
    RESET_ERROR_MESSAGE
    SET_ACTIVE_CASE
    SET_SECOND_LEVEL_QUESTION_DATA
    SET_THIRD_LEVEL_QUESTION_DATA
    SET_FOURTH_LEVEL_QUESTION_DATA
    QUEST_PAGE_SUBMITTED
    SET_NEXT_STEP_PAGE
    REMOVE_FORM_SELECTED_PROPERTY
    APPEND_TO_PROPERTY
    DELETE_SELECTED_PROPERTY
    DELETE_PROPERTIES_SUCCESS
  `)
}
